language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rabihmaj/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true rabihmaj/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-578544437536"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"